### ISSUE TITLE
Blackbox-style tuning OSD

### ISSUE THREAD

**Issue by fujin** [BrainFPV/TauLabs#10]
It would be dope to have live graphs from the motors, gyros and so-forth to assist with fine-tuning, I would have a whole page dedicated to it, between that and the OSD MENU, you would be able to do such an advanced level of tuning and measurement at the field without a GCS!

It would be really nice to see that stuff during autotune for example :chart_with_upwards_trend: 

check out this vid for the cleanflight blackblox running on sparky https://www.youtube.com/watch?v=Y3LtlA_eEAc ; overlaid with video post-edit I think

**Comment by BrainFPV** [comment]
I agree that the cleanflight backbox visualization looks pretty cool. However, I'm not sure how useful it would be to inegrate this into the OSD. The resolution is limited and it would be difficult to make sense of the data while flying. A better approach IMO is to visualize the data after the flight by overlaying them onto a HD video (like cleanflight does). The Brain has internal logging, so it would be a matter of writing the offline visualization.

I'm closing this as it is not Brain specific and will open an issue on Tau Labs as somethign to work on in the future.

Cheers

PS: I want to see some more crazy Blackout flights from you ;)
