### ISSUE TITLE
Disabling Current Monitoring doesn't disable Battery Flighttime alerts

### ISSUE THREAD

**Issue by pimvanpelt** [BrainFPV/TauLabs#23]
As seen on BrainFPV with Brain-20150213-r1, disabling current monitoring will still compute erratic/floating current values, and increment mAh usage, eventually refusing to arm the FC because of Flighttime alerts.

Reproduce:
- install BrainFPV w/ voltage monitoring turned on, but current monitoring turned off; configure a 3S battery at 2200mAh
- Connect battery to the unit - full battery will sense on ADC1 and leak to ADC0 pulling it high.
- Observe erratic current drain even though current monitoring is off (can be seen in GCS and on OSD)
- Wait until the phantom current draw adds up sufficient mAh power consumption (nearing 2200mAh)
- Alarm goes off for 'less than 60s of flight time at current battery consumption'
- Wait ..
- Alarm goes off for 'less than 30s of flight time at current battery consumption'
- Arm FC

Expected: FC arms and you can fly.

Observed: FC refuses to arm, battery is considered discharged beyond safe flight parameter.

Workaround: Set ADC0 sensitivity to 0mV/A which makes current draw jump to 'inf', disabling the power consumption integral, never reaching alarm state.

Suggested fix: disable the integral entirely when current monitoring is turned off, regardless of ADC sensitivity (perhaps zero the current always). 
Suggested fix: disable rendering current in OSD and GCS when current monitoring is turned off.

This may be present upstream in taulabs as well - I can check if you'd like (I don't currently have a regular Taulabs FC to check on).

**Comment by BrainFPV** [comment]
Thanks for reporting this. It is indeed a bug. Note that you can also work-around it by setting the ADC pin to `NONE`. 

I'm closing this, as it has been fixed in upstream Tau Labs. See https://github.com/TauLabs/TauLabs/pull/1508
