### ISSUE TITLE
Maybe bug with gpu/accel filtering?

### ISSUE THREAD

**Issue by fujin** [BrainFPV/TauLabs#24]
I haven't been able to get a consistent tune out of my rigs since the new split filtering, worse still, with mpu rate @ 1khz and 250hz lpf gyro, the cpu pegs at something like 80%.

I keep getting pitch noise of like 1000+ from a machine previously pulling 18msec taus. Any ideas? I plan to replace all of the motors in case, already identified one that was looking kind of worn.

**Comment by BrainFPV** [comment]
Thanks for the report. This has been fixed: https://github.com/BrainFPV/TauLabs/commit/af84efa74130d1afdf08712206d8b4fef5520e0f
