### ISSUE TITLE
1khz MPU rate + BLHeli14 sporadic/failure to arm

### ISSUE THREAD

**Issue by fujin** [BrainFPV/TauLabs#27]
With the Brain set to 1khz MPU rate, BLHeli14 doesn't want to arm up nicely on my RG20s. If I'm lucky one will idle correctly (low tone). Frankly, it is scary. https://www.youtube.com/watch?v=GleKYCgpkrc

Setting the MPU rate back to 500hz fixes it :( I have a sparky2 here I'm going to test with as well to see if it's isolated to BrainFPV.

Thoughts? Anyone able to reproduce?

**Comment by tracernz** [comment]
Are the ESCs known to work at this frequency?

**Comment by fujin** [comment]
@tracernz @borisbstyle is running them at 800usec here https://www.youtube.com/watch?v=y-8dQA8U3HE -- 1.25khz

**Comment by fujin** [comment]
@tracernz I will dig out some other gear and try to reproduce running them at at least 1000usec ideally.

**Comment by fujin** [comment]
Also worth mentioning I suppose that the ESCs have "PWM Input" turned to off, which more or less makes them only accept oneshot signals as far as I understand it.

**Comment by BrainFPV** [comment]
@fujin thanks for reporting it.  I would be surprised if this is Brain specific; it seems more likely to be an issue with that particular ESC. Let me know if you can reproduce this on sparky 2.

**Comment by borisbstyle** [comment]
I tried 1khz and even more on SPRACINGF3 and NAZE and both work fine on RG20 and SN20

**Comment by fujin** [comment]
@sskaug was kind enough to supply me with a testing firmware for RG20/DYS SN20 which fixes the 1khz issue. closing.
