### ISSUE TITLE
GCS crashes on launch (Win 7 x64)

### ISSUE THREAD

**Issue by tgreer** [BrainFPV/TauLabs#4]
GCS Version: Brain-20141123_win32_r2
OS: Windows 7 x64

Self extraction runs fine, extracts the folders. Running the taulabsgcs both normally and as Administrator crashes when it loads the main window.

![capture21](https://cloud.githubusercontent.com/assets/4996098/5600302/4eef1f6e-92cf-11e4-973f-d182cae7cd22.PNG)

**Comment by BrainFPV** [comment]
Thanks for the report. What graphics card are you using? If you are running it in VirtualBox, do you have 3d acceleration enabled?

**Comment by tgreer** [comment]
Intel HD Graphics 4400

**Comment by BrainFPV** [comment]
Not in VirtualBox, correct?

**Comment by tgreer** [comment]
Correct, this is an actual windows laptop

**Comment by BrainFPV** [comment]
Please try downloading the OpenGL dll for 64 bit systems and place it in the gcs/bin directory (overwrite the existing one), see here: https://github.com/TauLabs/TauLabs/wiki/Running-the-GCS-on-non-OpenGL-2.1-capable-systems

**Comment by tgreer** [comment]
That appears to fix the issue

**Comment by BrainFPV** [comment]
Great! Thanks for the testing.

**Comment by tgreer** [comment]
Is that something I should have picked up from documentation, or is that a
known bug to be fixed?

**Comment by BrainFPV** [comment]
@UKTamo it's a known bug with intel graphics cards. I added a note to the website.
