### ISSUE TITLE
GCS Crashes on launch (OSX 10.10 Yosemite)

### ISSUE THREAD

**Issue by tgreer** [BrainFPV/TauLabs#5]
Latest GCS crashes on launch.

OS: OSX 10.10 Yosemite
Version: Brain-20141123

**Comment by tgreer** [comment]
Tested against Intel HD 4000 and NVIDIA GeForce GT 650M both with the same issue

**Comment by tgreer** [comment]
The latest Tau Labs GCS direct from Tau Labs doesn't crash. FYI

**Comment by BrainFPV** [comment]
I just tested it on a MacBook Pro 2012 Retina with OS-X 10.8.2 and  NVIDIA GeForce GT 650M, works without problems. I will build a version using Yosemite to see if it helps.

**Comment by BrainFPV** [comment]
@UKTamo please try this version built on OS-X 10.10.1:

http://www.brainfpv.com/static/media/downloads/Brain-20141123_r2.dmg

**Comment by tgreer** [comment]
FWIW you need a better file mirror... 86KB/sec is terrible! Happy to help there! Downloading now to test

**Comment by tgreer** [comment]
I can confirm that version at least launches on OS X 10.10.1

I will test further in the morning to see if I can make it crash.

**Comment by tgreer** [comment]
Able to replicate the crash issue by going to Flight Data with no FC connected. Application crashes and then cannot relaunch. Back to square 1.

**Comment by BrainFPV** [comment]
@UKTamo Can you give this a try. It works for me on Yosemite:

http://www.brainfpv.com/static/media/downloads/Brain-20141123_r3.dmg

**Comment by tgreer** [comment]
Hi, This seems massively more stable. I've been unable to make it crash as of yet. I will keep testing and report back any problems, but this is a great improvement over r1 and r2.

Thanks

**Comment by BrainFPV** [comment]
@UKTamo Great! The differences between the versions is only the Qt version used. r1 was built with Qt 5.3.2, which has problem with the serial ennumeration, r2 with Qt 5.4, which has some other problem, and r3 with Qt 5.3.1 (which is also used for the official Tau Labs release.. should have checked first).

**Comment by tgreer** [comment]
Lovely.

In the mean time i've mirrored it here:
http://tsone.net.uk/Brain-20141123_r3.dmg as your mirrors are woefully
slow. I'd like to help with that.. contact me off github to sort that out :)

Regards

Thomas

**Comment by chadkouse** [comment]
I'm having the same issue with the latest release and yosemite: `Brain-20150720-r1.dmg`  - crashes on startup..
I'm sure this is no help but:
![console log](https://cldup.com/s7FHhEOq3k.png)

**Comment by BrainFPV** [comment]
@chadkouse try downloading it again. There was a packing problem with the version that was first uploaded.
