### ISSUE TITLE
Incorrect USB ID in TauLabs-CDC.inf prevents driver from loading

### ISSUE THREAD

**Issue by mattcamp** [BrainFPV/TauLabs#6]
TauLabs-CDC.inf does not contain a valid ID matching the Brain (USB\VID_20A0&PID_4242&MI_00) which prevents windows from loading the driver.

**Comment by BrainFPV** [comment]
Thanks. Fixed, see 2128ea3106170dac8e5c834d80a9554abc6b5fab
