### ISSUE TITLE
TauLabs Next preview release

### ISSUE THREAD

**Issue by fujin** [BrainFPV/TauLabs#7]
Hi @BrainFPV!

I am just starting to mess with my board today. I attempted to build latest firmware and gcs from the Brain branch, but get a could not load firmware error from gcs, even though it builds OK.

Anyway, I wanted to reach out and ask what plans you have if any to catch up to the taulabs next preview release? http://forum.taulabs.org/viewtopic.php?f=18&t=480

Are there any tasks I can help with? I attempted rebasing your brain branch toward TauLabs/next recursively, which went well, but introduced a number of compile failures in points of the code that I don't think you had even touched, so I have to assume the rebase went poorly. I reset that branch, lol.

It looks like you've been merging the taulabs next branch into your brain branch as opposed to rebasing yours on top of next (from time to time). Do you find merging in this way easier to deal with?

Thanks in advance for any responses, looking forward to messing with MWRate as well as oneshot125 as soon as I can get some wombo combo custom Brain-future-next builds going.

cheers,

@fujin

**Comment by fujin** [comment]
ping @peabody124 you might be able to offer some wisdom here :pager: (sorry!)

**Comment by fujin** [comment]
![](https://fbcdn-sphotos-h-a.akamaihd.net/hphotos-ak-xpf1/v/t34.0-12/s526x395/10933256_389027514604515_1695458233_n.jpg?oh=a259b84be28018213d94dbf30c0b2030&oe=54BE257E&__gda__=1421752001_abc2f9060d3d5eec45fb1dc5ed94f82d)

**Comment by BrainFPV** [comment]
@fujin I usually update the brain branch to track TauLabs/next on a weekly basis, sorry for lagging behind. I just did so and also enbaled the FrSky S.Port Telemetry option, which had been missing.

Git rebase is not really suited as the brain branch has been shared with others and a rebase will overwrite the history. Git merge is better suited for that purpose. If you want to do the merge yourself, I suggest the following steps:

 Add taulabs remote

```
git remote add taulabs https://github.com/TauLabs/TauLabs.git
```

Make `next` branch track upstream Tau Labs

```
git branch -u taulabs/next next
```

Update next and brain

```
git checkout next
git pull
git checkout brain
git pull
```

Make a new branch an merge next into it

```
git checkout -b brain_update
git merge next
```

Resolve all merge conflicts, and make sure everything still  works.

Finally, you can push the `brain_update` branch to your github repo and open a pull request for it to be merged into the `brain` branch of BrainFPV/TauLabs.

I hope this makes sense ;).
