### ISSUE TITLE
Configurable MPU Rate re: OneShot125

### ISSUE THREAD

**Issue by fujin** [BrainFPV/TauLabs#8]
Hi @BrainFPV 

I'd like to see if it is possible to get a configurable MPU rate, per the 9502's little brother. It seems like they have some auto-divisor code to get the rate working in different LPF settings.

I checked over and it looks like we are hard coded at 500hz.

The reason I ask is  in the [OneShot branch](https://github.com/TauLabs/TauLabs/pull/1424), @ernieift mentions a higher MPU rate, having tested up to 2khz! I believe a higher MPU rate will allow for more accurate oneshots, although this is a very rudimentary understanding.

Thoughts?

cheers,

@fujin

**Comment by fujin** [comment]
see https://github.com/fujin/TauLabs/tree/brain-oneshot for a brain branch with oneshot merged as well.

**Comment by fujin** [comment]
I read some notes on the forums regarding something called ChibiOS for the OSD allowing the MPU to run at a higher rate, so consider closing/linking this issue to that. I have no idea what ChibiOS is but just tracking it here for posterity.

**Comment by BrainFPV** [comment]
@fujin thanks. Great flying in the OneShot video btw :). I will start looing into ChibiOS after the current release, it shouldnt't be terribly hard to port the Brain specific code over.

**Comment by BrainFPV** [comment]
This feature is now available in the `brain_chibios` branch. The plan is to switch to ChibiOS before the next release.

Closing this.
